//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLTRACKER.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name CheckModificationTimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckModificationTime", ReplyAction="*")]
        URLTRACKER.ServiceReference1.CheckModificationTimeResponse CheckModificationTime(URLTRACKER.ServiceReference1.CheckModificationTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckModificationTime", ReplyAction="*")]
        System.Threading.Tasks.Task<URLTRACKER.ServiceReference1.CheckModificationTimeResponse> CheckModificationTimeAsync(URLTRACKER.ServiceReference1.CheckModificationTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckModificationTimeforhttp", ReplyAction="*")]
        void CheckModificationTimeforhttp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckModificationTimeforhttp", ReplyAction="*")]
        System.Threading.Tasks.Task CheckModificationTimeforhttpAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckModificationTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckModificationTime", Namespace="http://tempuri.org/", Order=0)]
        public URLTRACKER.ServiceReference1.CheckModificationTimeRequestBody Body;
        
        public CheckModificationTimeRequest() {
        }
        
        public CheckModificationTimeRequest(URLTRACKER.ServiceReference1.CheckModificationTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckModificationTimeRequestBody {
        
        public CheckModificationTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckModificationTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckModificationTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public URLTRACKER.ServiceReference1.CheckModificationTimeResponseBody Body;
        
        public CheckModificationTimeResponse() {
        }
        
        public CheckModificationTimeResponse(URLTRACKER.ServiceReference1.CheckModificationTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckModificationTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckModificationTimeResult;
        
        public CheckModificationTimeResponseBody() {
        }
        
        public CheckModificationTimeResponseBody(string CheckModificationTimeResult) {
            this.CheckModificationTimeResult = CheckModificationTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : URLTRACKER.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<URLTRACKER.ServiceReference1.WebService1Soap>, URLTRACKER.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URLTRACKER.ServiceReference1.CheckModificationTimeResponse URLTRACKER.ServiceReference1.WebService1Soap.CheckModificationTime(URLTRACKER.ServiceReference1.CheckModificationTimeRequest request) {
            return base.Channel.CheckModificationTime(request);
        }
        
        public string CheckModificationTime() {
            URLTRACKER.ServiceReference1.CheckModificationTimeRequest inValue = new URLTRACKER.ServiceReference1.CheckModificationTimeRequest();
            inValue.Body = new URLTRACKER.ServiceReference1.CheckModificationTimeRequestBody();
            URLTRACKER.ServiceReference1.CheckModificationTimeResponse retVal = ((URLTRACKER.ServiceReference1.WebService1Soap)(this)).CheckModificationTime(inValue);
            return retVal.Body.CheckModificationTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URLTRACKER.ServiceReference1.CheckModificationTimeResponse> URLTRACKER.ServiceReference1.WebService1Soap.CheckModificationTimeAsync(URLTRACKER.ServiceReference1.CheckModificationTimeRequest request) {
            return base.Channel.CheckModificationTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<URLTRACKER.ServiceReference1.CheckModificationTimeResponse> CheckModificationTimeAsync() {
            URLTRACKER.ServiceReference1.CheckModificationTimeRequest inValue = new URLTRACKER.ServiceReference1.CheckModificationTimeRequest();
            inValue.Body = new URLTRACKER.ServiceReference1.CheckModificationTimeRequestBody();
            return ((URLTRACKER.ServiceReference1.WebService1Soap)(this)).CheckModificationTimeAsync(inValue);
        }
        
        public void CheckModificationTimeforhttp() {
            base.Channel.CheckModificationTimeforhttp();
        }
        
        public System.Threading.Tasks.Task CheckModificationTimeforhttpAsync() {
            return base.Channel.CheckModificationTimeforhttpAsync();
        }
    }
}
